on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies

      - run: pip install furo

      - name: Delete those pesky dead branches
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v1
        with:
          github_token: ${{ github.token }}
          last_commit_age_days: -1

          # Disable dry run and actually get stuff deleted
          dry_run: no

      - name: Build and Commit
        uses: sphinx-notes/pages@v2

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
